// var sectors = [
//   "T.I",
//   "DESENVOLVIMENTO ",
//   "AMBULATORIO ",
//   "COMPRAS ",
//   "CONTROLADORIA ",
//   "ENGENHARIA DE PRODUTO ",
//   "ENGENHARIA DE TESTE/PROCESSO ",
//   "ESTOQUE ",
//   "EXPEDIÇÃO ",
//   "IMPORTAÇÃO ",
//   "SMT ",
//   "ÁREA TECNICA ",
//   "RECEBIMENTO",
//   "FACILITES ",
//   "SEGURANÇA E MONITORAMENTO ",
//   "QUALIDADE ",
//   "CERTIFICAÇÕES ",
//   "PCP ",
//   "PCM ",
//   "RH ",
//   "SESMT ",
//   "FISCAL",
// ];

// var propiedades = [
//   "Selecione um ",
//   "CALLIDUS",
//   "TECTOY",
//   "VICTUM",
//   "ETTERA",
//   "AMAZONAS INOVARE",
//   "TÁ NA PORTA",
// ];
